import os

GOOGLE_SERVICE_JSON = "GOOGLE_SERVICE_JSON"
STORY_STORAGE_DOC = "STORY_STORAGE_DOC"
API_KEYS_SHEET = "API_KEYS_SHEET"
MODEL_STORAGE_SHEET = "MODEL_STORAGE_SHEET"
VIDEO_DATE_ENV = "VIDEO_DATE"
VIDEO_NUMBER_ENV = "VIDEO_NUMBER"
CHARACTER_MODE_ENV = "CHARACTER_MODE"
LOCAL_FALLBACK_ENV = "LOCAL_FALLBACK"
MAX_SEGMENTS_ENV = "MAX_SEGMENTS"
UPLOAD_CATBOX_ENV = "UPLOAD_CATBOX"

DEFAULT_GROQ_MODEL = "llama-3.1-8b-instant"
DEFAULT_GEMINI_MODEL = "gemini-2.5-flash-lite"
DEFAULT_NVIDIA_MODEL = "meta/llama-3.1-8b-instruct"
DEFAULT_WORKERS_AI_MODEL = "@cf/meta/llama-3.1-8b-instruct"
DEFAULT_OPENROUTER_MODEL = "meta-llama/llama-3.1-8b-instruct:free"

BD_TZ_OFFSET_HOURS = 6
MAX_DOC_ENTRY_CHARS = 12000
DIALECT_BLOCK_CHARS = 1500
TTS_CHUNK_CHARS = 400
WORDS_PER_SECOND = 2.5
DEFAULT_MAX_SEGMENTS = 10
MIN_SEGMENT_WORDS = 20
MAX_SEGMENT_WORDS = 35
AVG_WORDS_PER_SEGMENT = 28
MIN_PLANNED_DURATION_SEC = 3.0
LLM_TIMEOUT_SEC = 90
HF_TIMEOUT_SEC = 300
